name: DirectPower
on: workflow_dispatch
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize Space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get clean

      - name: Force Download
        run: |
          URL=$(echo "aHR0cHM6Ly9hcmNoaXZlLm9yZy9kb3dubG9hZC9mcmVzaC13b21lbi1zZWFzb24tMS12LTAuMTAuMS9GcmVzaCUyMFdvbWVuLVNlYXNvbiUyMDEtdjAuMTAuMS1wYy56aXA=" | base64 --decode)
          # שימוש ב-curl עם פקודת המשך אוטומטית
          curl -L -C - -o "game_data.part" "$URL" --user-agent "Mozilla/5.0" --retry 10 --retry-delay 5

      - name: Split & Upload
        uses: actions/upload-artifact@v4
        with:
          name: game-output
          path: game_data.part
          retention-days: 1
