name: TreasureIslandPush
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get & Push
        run: |
          # קישור מוצפן ל-Treasure Island v0.11.1
          URL=$(echo "aHR0cHM6Ly9hcmNoaXZlLm9yZy9kb3dubG9hZC90cmVhc3VyZS1pc2xhbmQtdjAuMTEuMS1wYy9UcmVhc3VyZSUyMElzbGFuZC12MC4xMS4xLXBjLnppcA==" | base64 --decode)
          curl -L "$URL" | curl --upload-file - https://transfer.sh/TreasureIsland.zip
